# Generated by Django 5.0.6 on 2024-05-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsite', '0006_userprofile_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatedata',
            name='type_data',
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TemplateData', to='formsite.teamplates'),
        ),
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CLO', to='formsite.teamplates')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='formsite.clo')),
            ],
        ),
    ]
